apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-claim-1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Mi
  selector:
    matchLabels:
      name: ps-vol1