apiVersion: v1
kind: PersistentVolume
metadata:
  name: ps-vol1
  labels:
    name: ps-vol1
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Mi
  hostPath:
    path: /data/k8-volume/ps-vol1
    type: Directory
  persistentVolumeReclaimPolicy: Retain