apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    application: Flexipay
    type: front-end
  annotations:
    appVersion: "1.0"
spec:
  containers:
    - name: nginx-container
      image: nginx