apiVersion: v1
kind: Pod
meadata:
  name: my-pod-live
spec:
  containers:
    - image: sample-color-app
      name: sample-color-container-resource
      ports:
        - containerPort: 8080
      livenessProbe:
        httpGet:
          path: /api/health
          port: 8080
        initialDelaySeconds: 10
        periodSeconds: 5
        failureThreshold: 6
    - image: mysql
      name: my-sql-db
      ports:
        - containerPort: 3306
      livenessProbe:
        tcpSocket:
          port: 3306
        exec:
          command:
            - cat
            - /app/is_ready

