apiVersion: v1
kind: Pod
metadata:
  name: my-pod-secret1
spec:
  containers:
    - image: sample-color-app
      name: sample-color-container-secret1
      ports:
        - containerPort: 8080
      envFrom:
        - secretRef:
            name: app-secrets