apiVersion: v1
kind: Pod
metadata:
  name: my-pod-env-test
spec:
  containers:
    - image: simple-color-webapp
      name: simple-color-container
      ports:
        - containerPort: 8080
      env:
        - name: APP_COLOR
          value: blue