
apiVersion: v1
kind: Pod
metadata:
  name: my-pod-secret3
spec:
  containers:
    - image: sample-color-app
      name: sample-color-container-secret3
      ports:
        - containerPort: 8080
      volumes:
      - name: app-secret-volume
        secret:
          secretName: app-secrets