apiVersion: v1
kind: Pod
metadata:
  name: my-pod-configmap2
spec:
  containers:
    - image: sample-color-app
      name: sample-color-container2
      ports:
        - containerPort: 8080
      env:
        - name: APP_COLOR
          valueFrom:
            configMapKeyRef:
              name: my-config-map
              key: APP_COLOR