apiVersion: v1
kind: Pod
metadata:
  name: my-pod-configmap3
spec:
  containers:
    - image: sample-color-app
      name: sample-color-container3
      ports:
        - containerPort: 8080
      volumes:
        - name: app-config-volume
          configMap:
            name: my-config-map