apiVersion: v1
kind: Pod
metadata:
  name: my-pod-secret2
spec:
  containers:
    - image: sample-color-app
      name: sample-color-container-secret2
      ports:
        - containerPort: 8080
      env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_PASSWORD