apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc
  labels:
    app: Flexipay
    type: front-end
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        app: Flexipay
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 6