apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    type: front-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        type: front-end
    spec:
      containers:
        - image: nginx
          name: nginx-container
  replicas: 3